server {
    listen 8080;  #  Port différent de 80 pour éviter les conflits
    server_name localhost;

    # Définir le chemin racine pour accéder au backend PHP
    root /var/www/html/Backend/public;
    index index.php;

    # Route principale pour le backend, redirige les requêtes vers index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Gestion des fichiers PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass my-php-container:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
