server {
    listen 80;
    server_name localhost;

    # Racine des fichiers publics
    root /var/www/html/Frontend/public/;  
    index index.html;

    # Gestion des fichiers PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;  # Redirection des requêtes PHP vers le conteneur PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }

    # # Gestion des fichiers statiques comme JS et CSS pour éviter les erreurs de MIME
    # location / {
    #     try_files $uri $uri/ /pages/index.html;
    # }
       
    # Redirection vers la page d'accueil dans /pages/accueil.html
    location = / {
        try_files /pages/accueil.html =404;
    }
    # Routes vers les pages HTML dans le dossier /pages/
    location /pages/ {
        try_files $uri $uri/ =404;
    }

    # Proxy pour Vite en mode développement
    location /@vite/ {
        proxy_pass http://my-node-container:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* \.(js|css)$ {
        proxy_pass http://my-node-container:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
    }

    # Proxy pour les requêtes API
    location /api/ {
        proxy_pass http://my-php-container:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}